### ISSUE TITLE
How to store amount values - like Stripe?

### ISSUE THREAD

**Issue by DevinWalker** [DevinWalker/give-io-documentation#2]
## Issue Overview

I see current API docs that amount fields are using 6 decimal spaces. I'm thinking this may not be the best idea. 

We're using Stripe for the main payment processor for this platform so I think we should be storing amounts as they do: https://stripe.com/docs/currencies#zero-decimal

> All API requests expect amounts to be provided in a currency’s smallest unit. For example, to charge $10 USD, provide an amount value of 1000 (i.e, 1000 cents).
> 
> For zero-decimal currencies, still provide amounts as an integer but without multiplying by 100. For example, to charge ¥500, simply provide an amount value of 500.

**Comment by MikePayne** [comment]
Yeah, this makes sense. My notes from our last meeting said to use the decimal point approach, but it makes way more sense to store it in the format that Stripe will want.

**Comment by DevinWalker** [comment]
Cool 👍
